version: "2"

services:
  gateway:
    image: nexus.techolution.com:8123/screenings/gateway:release
    networks:
      - my-network
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - eureka
    environment:
      - SPRING_PROFILES_ACTIVE=release

  interview-server:
    image: nexus.techolution.com:8123/screenings/interview-server:release
    networks:
      - my-network
    ports:
      - "8081:8081"
    expose:
      - "8081"
    depends_on:
      - eureka
    environment:
      - SPRING_PROFILES_ACTIVE=release
      
  assessment-server:
    image: nexus.techolution.com:8123/screenings/assessment-server:release
    networks:
      - my-network
    ports:
      - "8084:8084"
    expose:
      - "8084"
    depends_on:
      - redis
      - eureka
    environment:
      - SPRING_PROFILES_ACTIVE=release

  position-server:
    image: nexus.techolution.com:8123/screenings/position-server:release
    networks:
      - my-network
    ports:
      - "8083:8083"
    expose:
      - "8083"
    depends_on:
      - eureka
    environment:
      - SPRING_PROFILES_ACTIVE=release

  skill-server:
    image: nexus.techolution.com:8123/screenings/skill-server:release
    networks:
      - my-network
    ports:
      - "8082:8082"
    expose:
      - "8082"
    depends_on:
      - eureka
    environment:
      - SPRING_PROFILES_ACTIVE=release


  eureka:
    image: springcloud/eureka
    networks:
      - my-network
    ports:
      - "8761:8761"
    expose:
      - "8761"

  redis:
    image: redis
    networks:
      - my-network
    ports:
      - "6379:6379"
    expose:
      - "6379"


networks:
  my-network:
    driver: bridge
