version: "2"

services:
  gateway:
    image: nexus.techolution.com:8123/screenings/gateway
    networks:
      - my-network
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - eureka

  interview-server:
    image: nexus.techolution.com:8123/screenings/interview-server
    networks:
      - my-network
    ports:
      - "8081:8081"
    expose:
      - "8081"
    depends_on:
      - interview-db
      - eureka

  position-server:
    image: nexus.techolution.com:8123/screenings/position-server
    networks:
      - my-network
    ports:
      - "8083:8083"
    expose:
      - "8083"
    depends_on:
      - mongo
      - eureka

  skill-server:
    image: nexus.techolution.com:8123/screenings/skill-server
    networks:
      - my-network
    ports:
      - "8082:8082"
    expose:
      - "8082"
    depends_on:
      - mongo
      - eureka

  mongo:
    image: mongo
    networks:
      - my-network
    ports:
      - "27017:27017"
    expose:
      - "27017"

  eureka:
    image: springcloud/eureka
    networks:
      - my-network
    ports:
      - "8761:8761"
    expose:
      - "8761"
  redis:
    image: redis
    networks:
      - my-network
    ports:
      - "6379:6379"
    expose:
      - "6379"

  interview-db:
      image: mysql:latest
      environment:
        - MYSQL_ROOT_PASSWORD=admin123
        - MYSQL_USER=dbuser
        - MYSQL_PASSWORD=password
        - MYSQL_DATABASE=interview
  #    volumes:
  #      - mysql-data:/home.scripts
  #    working_dir: "/home/scripts"
      networks:
        - my-network
      ports:
        - "3306:3306"
      expose:
        - "3306"

networks:
  my-network:
    driver: bridge
