version: "2"

services:
  vrcms:
    image: nexus.techolution.com:8123/vrcms
    networks:
      - cms-network
    ports:
      - "8081:8081"
    expose:
      - "8081"
    depends_on:
      - mongo
      - eureka
  krpano:
    image: nexus.techolution.com:8123/krpano
    networks:
      - cms-network
    ports:
      - "8082:8082"
    expose:
      - "8082"
    depends_on:
      - eureka
  gateway:
    image: nexus.techolution.com:8123/gateway
    networks:
      - cms-network
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - eureka
      - krpano
      - vrcms      
  imageman:
    image: nexus.techolution.com:8123/imageman
    networks:
      - cms-network
    ports:
      - "8083:8083"
    expose:
      - "8083"
    depends_on:
      - eureka
      
  eureka:
    image: springcloud/eureka
    networks:
      - cms-network
    ports:
      - "8761:8761"
    expose:
      - "8761"
  mongo:
    image: mongo
    networks:
      - cms-network
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - /home/ubuntu/data/vrcms:/data/db
      
  svapp:
    image: nexus.techolution.com:8123/svapp 
    ports:
      - "1337:1337"
      - "3000:3000"
      - "5050:5050"

                
networks:
  cms-network:
    driver: bridge
